[build]
  base = "frontend"
  command = "npm run build"
  publish = "build"
  
[build.environment]
  REACT_APP_API_URL = "https://remote-jobs-backend.onrender.com/api"
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[plugins]]
package = "netlify-plugin-cypress"

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "production" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 