[build]
  # This will be frontend build path when available
  # publish = "frontend/build"
  # For now, set up a placeholder static page
  publish = "static"
  command = "mkdir -p static && echo '<html><body><h1>Remote Jobs Monitor</h1><p>API is available at <a href=\"https://remote-jobs-api.onrender.com\">https://remote-jobs-api.onrender.com</a></p></body></html>' > static/index.html"
  base = "frontend"
  publish = "build"
  command = "npm run build"

# Redirects and proxy for API when frontend is available
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables
[context.production.environment]
  NETLIFY_SITE_NAME = "remote-jobs"

[context.deploy-preview.environment]
  NETLIFY_SITE_NAME = "remote-jobs-preview"

# Dev environment
[dev]
  framework = "#custom"
  command = "python -m http.server -d static 8000"
  port = 8000
  targetPort = 8000
  publish = "static"

# Build plugin
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Headers for the site
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self' https://remote-jobs-api.onrender.com;"

[build.environment]
  REACT_APP_API_URL = "https://remote-jobs-monitor-backend.onrender.com"
  NODE_VERSION = "18" 